plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
